os: windows
language: "bash"
before_install:
  - choco install python
  - "pip3 install -r requirements-testing.txt"
script:
  - coverage run -m pytest main-testing.py
  - bash <(curl -s https://codecov.io/bash)