sudo: false
dist: "trusty" # otherwise 'python3-pip' won't be available
language: "python"
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
before_install:
  - "pip3 install -r requirements-testing.txt"
script:
- sudo pip install requirements-testing.txt
- coverage run -m pytest main-testing.py
- bash <(curl -s https://codecov.io/bash)